"""Pre-build step: gzip the static web assets into a generated header.

The web portal serves ~90 KB of HTML/CSS/JS straight out of flash, and this
board is already at ~91% of its app partition. Compressing the blobs at build
time trades a few seconds of build for roughly 50 KB of flash, and the browser
does the decompression for free via Content-Encoding: gzip.

The authoring files under src/WebServer/Pages/ stay the source of truth; they
are no longer #included by any translation unit, so the uncompressed text is
never linked in. The generated header lands in the build directory (not in
src/) so a binary blob never enters git.
"""

import gzip
import os
import re

Import("env")  # noqa: F821  (injected by PlatformIO/SCons)

PROJECT_DIR = env["PROJECT_DIR"]  # noqa: F821
PAGES = os.path.join(PROJECT_DIR, "src", "WebServer", "Pages")

# (generated symbol, source file, literal name)
ASSETS = [
    ("ASSET_CONFIG_CSS",          "CommonStyles.h",      "COMMON_CSS"),
    ("ASSET_TELEMETRY_HTML",      "TelemetryPage.h",     "TELEMETRY_PAGE_HTML"),
    ("ASSET_TELEMETRY_JS",        "TelemetryPage.h",     "TELEMETRY_PAGE_JS"),
    ("ASSET_CONFIG_POWER_HTML",   "ConfigPowerPage.h",   "CONFIG_POWER_PAGE_HTML"),
    ("ASSET_CONFIG_POWER_JS",     "ConfigPowerPage.h",   "CONFIG_POWER_PAGE_JS"),
    ("ASSET_CONFIG_THERMAL_HTML", "ConfigThermalPage.h", "CONFIG_THERMAL_PAGE_HTML"),
    ("ASSET_CONFIG_THERMAL_JS",   "ConfigThermalPage.h", "CONFIG_THERMAL_PAGE_JS"),
    ("ASSET_CONFIG_BMS_HTML",     "ConfigBmsPage.h",     "CONFIG_BMS_PAGE_HTML"),
    ("ASSET_CONFIG_BMS_JS",       "ConfigBmsPage.h",     "CONFIG_BMS_PAGE_JS"),
    ("ASSET_CONFIG_SYSTEM_HTML",  "ConfigSystemPage.h",  "CONFIG_SYSTEM_PAGE_HTML"),
    ("ASSET_CONFIG_SYSTEM_JS",    "ConfigSystemPage.h",  "CONFIG_SYSTEM_PAGE_JS"),
]


def extract(path, name):
    source = open(path, "r", encoding="utf-8").read()
    pattern = re.escape(name) + r"\s*(?:\[\s*\])?\s*(?:PROGMEM\s*)?=\s*R\"rawliteral\((.*?)\)rawliteral\";"
    match = re.search(pattern, source, re.S)
    if not match:
        raise RuntimeError("gen_web_assets: literal %s not found in %s" % (name, path))
    return match.group(1)


def emit(handle, symbol, raw):
    # mtime=0 keeps the output byte-identical across builds, so an unchanged
    # asset does not churn the firmware image.
    blob = gzip.compress(raw.encode("utf-8"), compresslevel=9, mtime=0)
    handle.write("static const uint8_t %s[] PROGMEM = {\n" % symbol)
    for i in range(0, len(blob), 16):
        row = ", ".join("0x%02x" % b for b in blob[i:i + 16])
        handle.write("    %s,\n" % row)
    handle.write("};\n")
    handle.write("static const size_t %s_LEN = %d;\n\n" % (symbol, len(blob)))
    return len(raw.encode("utf-8")), len(blob)


def main():
    out_dir = os.path.join(env.subst("$BUILD_DIR"), "generated")  # noqa: F821
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "WebAssetsGz.h")

    raw_total = 0
    gz_total = 0
    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write("// Generated by scripts/gen_web_assets.py - do not edit.\n")
        handle.write("// Source of truth: src/WebServer/Pages/*.h\n")
        handle.write("#pragma once\n\n#include <Arduino.h>\n\n")
        for symbol, filename, literal in ASSETS:
            raw = extract(os.path.join(PAGES, filename), literal)
            raw_len, gz_len = emit(handle, symbol, raw)
            raw_total += raw_len
            gz_total += gz_len

    env.Append(CPPPATH=[out_dir])  # noqa: F821
    print("gen_web_assets: %d assets, %d -> %d bytes (%.0f%% saved)"
          % (len(ASSETS), raw_total, gz_total, 100.0 * (1 - gz_total / float(raw_total))))


main()
