#define SERIAL_DEBUG false

#define ENABLED_CRUISE_CONTROL true

#define THROTTLE_CHANNEL 1

#define THROTTLE_PIN 3

#define CANBUS_INT_PIN 2
#define CANBUS_SCK_PIN 13
#define CANBUS_SI_PIN 11
#define CANBUS_SO_PIN 12
#define CANBUS_CS_PIN 10

#define CURRENT_PIN A0
#define VOLTAGE_PIN A1
#define ESC_TEMPERATURE_PIN A2
#define MOTOR_TEMPERATURE_PIN A3

#define CALIBRATION_PULSES_MIN 916
#define CALIBRATION_PULSES_MID 1492
#define CALIBRATION_PULSES_MAX 1800

#define PWM_FRAME_TIME_MS 56
