#define ENABLED_CRUISE_CONTROL true
#define ENABLED_POWER_LIMIT true
#define POWER_LIMIT_PERCENTAGE 80

#define MOTOR_TEMPERATURE_PIN A0

#define THROTTLE_PIN A1
#define THROTTLE_PIN_MIN 170
#define THROTTLE_PIN_MAX 850
#define THROTTLE_RECOVERY_PERCENTAGE 25

#define BUTTON_PIN 3
#define BUZZER_PIN 4

#define BATTERY_MAX_CURRENT 140
#define BATTERY_CONTINUOS_CURRENT 105
#define BATTERY_MIN_VOLTAGE 462
#define BATTERY_MAX_VOLTAGE 588

#define MOTOR_MAX_TEMP 60

#define ESC_PIN 9
#define ESC_MIN_PWM 1050
#define ESC_MAX_PWM 1950

#define ESC_MAX_TEMP 110
#define ESC_MAX_CURRENT 200
#define ESC_CONTINUOS_CURRENT 80

#define CANBUS_INT_PIN 2
#define CANBUS_SCK_PIN 13
#define CANBUS_SI_PIN 11
#define CANBUS_SO_PIN 12
#define CANBUS_CS_PIN 10
